name: bizil
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase & Google Sign-In
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  google_sign_in: ^7.2.0

  # State management
  provider: ^6.1.1

  # Speech & AI
  speech_to_text: ^7.3.0
  flutter_tts: ^4.0.0
  tflite_flutter: ^0.11.0

  # Networking
  http: ^1.2.2

  # UI & Design
  lottie: ^3.0.0
  font_awesome_flutter: ^10.7.0
  confetti: ^0.8.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  intl: ^0.20.2
  uuid: ^4.3.3
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true
  assets:
    - assets/model.tflite
    - assets/labels.txt
    - assets/vocabulary.txt

# --- App Icon Configuration ---
flutter_icons:
  android: true
  ios: true
  image_path: "assets/Images/Kushi App Logo.png"
